/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    galleries: Gallery;
    exhibitions: Exhibition;
    artworks: Artwork;
    submissions: Submission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  appRole?: ('admin' | 'artist' | 'gallery' | 'juror' | 'user') | null;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  name: string;
  slug: string;
  location: string;
  bio?: string | null;
  logo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  /**
   * Commission rate (%) for artwork sales
   */
  commissionRate?: number | null;
  /**
   * The gallery user who owns this entry.
   */
  owner: number | User;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  cover_image: number | Media;
  gallery: number | Gallery;
  start_date: string;
  end_date: string;
  /**
   * Deadline for artists to submit their work
   */
  submission_deadline: string;
  /**
   * Enter fee in dollars (e.g., 35)
   */
  submission_fee: number;
  /**
   * Platform fee percentage (e.g., 10 for 10%)
   */
  platformFeePercentage: number;
  /**
   * Maximum number of artworks that can be selected for this exhibition
   */
  max_selected: number;
  /**
   * Current number of selected artworks
   */
  selectedCount?: number | null;
  /**
   * Assign jurors to review submissions
   */
  jurors?: (number | User)[] | null;
  /**
   * Current stage of the exhibition
   */
  exhibitionStatus: 'open' | 'jury_review' | 'finalized' | 'on_display' | 'completed';
  /**
   * Total number of submissions received
   */
  totalSubmissions?: number | null;
  /**
   * Total revenue from submission fees
   */
  totalRevenue?: number | null;
  juryProgress?: {
    totalReviewed?: number | null;
    accepted?: number | null;
    rejected?: number | null;
  };
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  image: number | Media;
  /**
   * Additional images of the artwork
   */
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  category: 'painting' | 'sculpture' | 'photography' | 'digital' | 'mixed_media' | 'print' | 'drawing' | 'other';
  /**
   * e.g., "Oil on canvas"
   */
  medium?: string | null;
  /**
   * Detailed materials description
   */
  materials?: string | null;
  /**
   * Physical dimensions of the artwork
   */
  dimensions: {
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Depth (optional, for sculptures and 3D works)
     */
    depth?: number | null;
    unit: 'in' | 'cm';
  };
  /**
   * Auto-generated dimension string
   */
  dimensionsDisplay?: string | null;
  /**
   * Year created
   */
  year?: number | null;
  /**
   * Edition info (e.g., "1/10" for limited editions)
   */
  edition?: string | null;
  owner: number | User;
  sale_status?: ('not_for_sale' | 'for_sale' | 'pending' | 'sold') | null;
  /**
   * Current asking price
   */
  price?: number | null;
  /**
   * Actual sold price
   */
  sold_price?: number | null;
  sold_date?: string | null;
  buyer?: (number | null) | User;
  /**
   * Buyer full name
   */
  buyer_name?: string | null;
  /**
   * Buyer email or phone
   */
  buyer_contact?: string | null;
  payment_method?: ('cash' | 'card' | 'app' | 'other') | null;
  /**
   * Auto-calculated gallery commission
   */
  commission_amount?: number | null;
  sale_notes?: string | null;
  /**
   * Assigned by the gallery after acceptance
   */
  label_number?: string | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title?: string | null;
  artist: number | User;
  exhibition: number | Exhibition;
  artwork: number | Artwork;
  /**
   * Artist name(s) to display on exhibition tags. Array of strings, e.g. ["Jane Doe", "John Smith"]
   */
  displayArtists?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set by Jurors during the selection process.
   */
  juryStatus?: ('pending' | 'accepted' | 'rejected') | null;
  /**
   * Jurors assigned to review this submission
   */
  assignedJurors?: (number | User)[] | null;
  /**
   * Final selection status by the Gallery.
   */
  galleryStatus?: ('pending' | 'selected' | 'not_selected') | null;
  paymentStatus?: ('pending' | 'paid' | 'waived') | null;
  /**
   * Submission fee amount
   */
  paymentAmount?: number | null;
  paymentDate?: string | null;
  /**
   * Stripe/PayPal transaction ID
   */
  paymentTransactionId?: string | null;
  submittedAt?: string | null;
  /**
   * When the jury reviewed this submission
   */
  reviewedAt?: string | null;
  /**
   * Private notes from jurors (not visible to artists)
   */
  juryNotes?: string | null;
  reviewHistory?:
    | {
        reviewer?: (number | null) | User;
        action?: ('accepted' | 'rejected' | 'pending') | null;
        timestamp?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  appRole?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  location?: T;
  bio?: T;
  logo?: T;
  email?: T;
  phone?: T;
  website?: T;
  commissionRate?: T;
  owner?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  cover_image?: T;
  gallery?: T;
  start_date?: T;
  end_date?: T;
  submission_deadline?: T;
  submission_fee?: T;
  platformFeePercentage?: T;
  max_selected?: T;
  selectedCount?: T;
  jurors?: T;
  exhibitionStatus?: T;
  totalSubmissions?: T;
  totalRevenue?: T;
  juryProgress?:
    | T
    | {
        totalReviewed?: T;
        accepted?: T;
        rejected?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  category?: T;
  medium?: T;
  materials?: T;
  dimensions?:
    | T
    | {
        width?: T;
        height?: T;
        depth?: T;
        unit?: T;
      };
  dimensionsDisplay?: T;
  year?: T;
  edition?: T;
  owner?: T;
  sale_status?: T;
  price?: T;
  sold_price?: T;
  sold_date?: T;
  buyer?: T;
  buyer_name?: T;
  buyer_contact?: T;
  payment_method?: T;
  commission_amount?: T;
  sale_notes?: T;
  label_number?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  artist?: T;
  exhibition?: T;
  artwork?: T;
  displayArtists?: T;
  juryStatus?: T;
  assignedJurors?: T;
  galleryStatus?: T;
  paymentStatus?: T;
  paymentAmount?: T;
  paymentDate?: T;
  paymentTransactionId?: T;
  submittedAt?: T;
  reviewedAt?: T;
  juryNotes?: T;
  reviewHistory?:
    | T
    | {
        reviewer?: T;
        action?: T;
        timestamp?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}